config/routes.rb
Earth::Application.routes.draw do
  root  'pages#home'
   resources :pages
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/login',  to: 'sessions#new',         via: 'get'
  match '/logout', to: 'sessions#destroy',     via: 'delete'
  get "users/new"
  
  match '/news',    to: 'pages#news',    via: 'get'
  match '/about',   to: 'pages#about',   via: 'get'
  match '/login',   to: 'pages#login',   via: 'get'
  

end

app/models/earthquake.rb
class Earthquake < ActiveRecord::Base
end

app/models/station.rb
class Station < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
<<<<<<< HEAD

  protect_from_forgery
 

=======
#<<<<<<< HEAD
 # protect_from_forgery
 
#=======
>>>>>>> 231d11cdf2fbfa83575c9fdd139f6d20154f6fc4
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   include SessionsHelper
<<<<<<< HEAD

=======
#>>>>>>> a7535958f0ce70fa09ed9dcd76d632600b1809e8
>>>>>>> 231d11cdf2fbfa83575c9fdd139f6d20154f6fc4
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def login
  end
  def index
	  @stations = Station.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
	   render 'new'
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
def show
    @user = User.find(params[:id])
    
  end

  def new
	     @user = User.new
     end
     def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Earthquake App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  
  def home
	  require 'open-uri'
    require 'nokogiri'
    @earthquakes = Earthquake.all
  end
  def show
    
end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
def full_title(page_title)
    base_title = "Earthquake App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
def log_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end
  def logged_in?
    !current_user.nil?
  end
  def current_user=(user)
    @current_user = user
  end
  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  def log_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "News", '#' %></li>
    </ul>
  </nav>
</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Earthquake app", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
             <li><%= link_to "Home",    root_path %></li>
             <li><%= link_to "About",  about_path %></li>
              <li><%= link_to "Login", login_path %></li>
              <li><%= link_to "Sign up", '#'%></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
</div>

<div class="righttwitter">
    <a class="twitter-timeline" href="https://twitter.com/Earthquakeapp1" data-widget-id="446598676408848384">Tweets by @Earthquakeapp1</a>
    <script>
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
    if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";
    fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
    </script>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<<<<<<< HEAD
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Earthquake app", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
             <li><%= link_to "Home",    root_path %></li>
             <li><%= link_to "About",  about_path %></li>
              <li><%= link_to "Login", login_path %></li>
              <li><%= link_to "Sign up", signup_path%></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
=======
   <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
   </div>
</body>
>>>>>>> 231d11cdf2fbfa83575c9fdd139f6d20154f6fc4
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Earthquake Predictions!</p>
<p>Our application is very informative and gives you a view of recent earthquake activities across the guide.</p>
<p>Search our database to get your prediction today!</p>

app/views/pages/home.html.erb
<div class="center hero-unit">
<h1>Earthquake App</h1>
<p>Earthquake Predictions!</p>
<p>Our application is very informative and gives you a view of recent earthquake activities across the guide.</p>
<br>

<p><li><%= link_to "Sign up", '#' %> to view!</li></p>

app/views/pages/index.html.erb
<div class='unit one-of-two' data-no-turbolink>
	<% @stations.each do |s| %>
	<p>Trading Name: <%= link_to "#{s.trading_name}", page_path(s.id) %><br />
	Address1: <%= s.adress1 %><br />
	Address2<%= s.adress2 %><br />
	Address3<%= s.adress3 %>
	City<%= s.city %>
	Post Code<%= s.post_code %>
	Telephone<%= s.telephone %></p>
	<% end %>
</div>

app/views/pages/login.html.erb
<h1>Login</h1>
<p>Login Below</p>

app/views/pages/news.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Earthquake App | News</title>
</head>
<body>
<h1>News</h1>
<p>Earthquake Predictions!</p>
<p>Our application is very informative and gives you a view of recent earthquake activities across the guide.</p>
Search our database to get your prediction today!
</body> 
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_tweets.html.erb
<section id="tweets">
  <ul>
    <% @tweets.each do |tweet| %>
      <li><%= link_to tweet.text, "https://www.twitter.com/#{tweet.user.screen_name}" %></li>
  </ul>
</section>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
 <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>
<h1>Welcome <%= @user.name%> <ul class="nav pull-right"><li> <%= link_to "Log out", logout_path, method: "delete" %></li><li><%= link_to "Profile", current_user %></li></ul> </h1>


<div class='unit three-of-five'>
	<div class='unit one-of-two'>
		<p>You are currently viewing temperature data for <%= link_to "#{@capability.name}", page_path(@capability.id) %> for the following days:
	<p/>
	</div>
	<div class='unit one-of-two'>
	<% @docxml.xpath("//DV//Location//Period").each do |node| %>
	    <h5><%= format_day(node['value']) %></h5>
	<% end %>
	</div>
	<% @docxml.xpath("//DV//Location//Period").each do |node| %>
	    <h3>Day: <%= format_day(node['value']) %></h3>
			    <% node.xpath("//Rep").each do |r| %>
		<table>
			<thead>
				<tr>
					<th>Weather Type</th>
					<th>Temperature</th>
					<th>Wind Direction</th>
					<th>Wind Speed</th>
				</tr>
			</thead>
			<tbody>
			    <tr>
							<td><%= weather_type(r['W']) %></td>
							<td><%= r['T'] %></td>
							<td><%= r['D'] %></td>
							<td><%= r['S'] %></td>
						</tr>
						<!-- <br /><br />  -->
			    <% end %>
			</tbody>
		</table>
	<% end %>


</div>

<div class='unit two-of-five'>
     <div id="map_canvas"></div>
    <input id="address" type="hidden" placeholder="Aberdeen">
    <input type="hidden" value="Encode" onclick="codeAddress()">
</div>